### PR TITLE
fix build problem

### PR DESCRIPTION
**Pull request by tinybug-m**
This change will resolves the #324 issue

### CODE REVIEW

**Comment by tinybug-m** [comment]
Fixed the frontend build issue by ensuring npm install is run before building the frontend. This resolves any dependency-related problems and streamlines the build process.

**Comment by tinybug-m** [comment]
The web/html directory did not exist prior to this operation. The directory has now been successfully created to facilitate the organization of web-related files.

**Comment by alireza0** [comment]
Thank you!

**Comment by tinybug-m** [comment]
my glad

**Pull request merged**
